version: '3.8'

networks:
  dev:
    driver: bridge

services:
  
 
  appdb:
    container_name: appdb
    image: postgres:latest
    ports:
      - "5432:5432"

    restart: always  

    environment:
      POSTGRES_DB: smartshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kelly@postgres1
    volumes:
      - app_data:/var/lib/postgresql/data

    
   
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@kelly.com
      PGADMIN_DEFAULT_PASSWORD: kelly
    ports:
    - "5051:80"
    depends_on:
      - appdb
    

volumes:
  app_data:   